### ISSUE TITLE
Whitescreen/Freeze after leaving Settings

### ISSUE THREAD

**Issue by goldeneyeonline** [DS-Homebrew/TWiLightMenu#1804]
**Console Configuration:** Nintendo DSi, Unlaunch 2.0, NO Hiya
**TWiLight Menu++ Version:** 24.00
**TWiLight Menu++ Theme:** Nintendo 3DS light (but that doesn't matter)

### Expected behaviour

When exiting the TWM++ Settings (either by pressing (b) or by touching the navigation bar on the bottom of the Touchscreen), I expect to get back to TWM++ with my altered settings

### Actual behaviour

When exiting the TWM++ Settings (either method described above) I get a Whitescreen/Freeze. Nothing happens anymore. Seemingly random I can turnoff the DSi by pressing the powerbutton for a second or I have to force it down by pressing the powerbutton for 4-5 seconds.

Sidenote 1: Pretty sure that worked in way earlier versions...
Sidenote 2: Same thing happens when in TWM++ settings on "Misc. settings" tab I try to open "System Settings" (but I wasn't going to directly open 2 issues, maybe it's connected)

### Steps to reproduce

1. Boot TWM++
2. Open TWM++ Settings
3. Close Settings

**Comment by Vincydroid** [comment]
Console Configuration: Nintendo 2DS, Luma3DS 10.2.1
TWiLight Menu++ Version: 24.00
TWiLight Menu++ Theme: Nintendo 3DS light

The same issue occurs, but i can press HOME to get out of TwilightMenu

**Comment by lifehackerhansol** [comment]
Known issue, already fixed in https://github.com/DS-Homebrew/TWiLightMenu/commit/e6a71415131744ba370150dce96d3056ceb8db24.

You can download the nightly build to get around it.

**Comment by goldeneyeonline** [comment]
Hey! I confirm the issue is gone in 24.1.0!
Two questions if you allow:

1. I'm too dumb to find the nightly builds, or do I have to build them myself? :-)
2. The second bug I mentioned, which I thought might be connected and thus didn't open another ticket, still occurs: I still get white screen fix when opening system settings from twm settings. Sounds I open another ticket? 
TIA!!

**Comment by RocketRobz** [comment]
> I'm too dumb to find the nightly builds you mentioned, or do I have to build them myself? :-)

They're available here: https://github.com/TWLBot/Builds

> 2. The second bug I mentioned, which I thought might be connected and thus didn't open another ticket, still occurs: I still get white screen freeze when opening system settings from twm settings. Should I open another ticket?

No need. Commit 38fe3cbc will fix the issue.

**Comment by Epicpkmn11** [comment]
> 1. I'm too dumb to find the nightly builds you mentioned, or do I have to build them myself? :-)

Nightlies can be found in the [TWLBot/Builds](https://github.com/TWLBot/Builds) repo, more or less just download the same one you would for a normal release and install the same way. If you're on 3DS they can also be installed using Universal-Updater, simply select `[nightly] TWiLight Menu++`.

> 2. The second bug I mentioned, which I thought might be connected and thus didn't open another ticket, still occurs: I still get white screen freeze when opening system settings from twm settings. Should I open another ticket?
TIA!!

Make sure your `SysNAND region` is set correctly as I think that's used for loading System Settings, if it is then yeah probably good to open a new issue for that.

**Comment by goldeneyeonline** [comment]
Sorry guys for necrobumping this again, tried the "system settings" in 24.1.1 now (release notes say it's fixed), but I land in unlaunch filemenu (probably because of load error?!) instead of the system settings... Any ideas? :-)
