### ISSUE TITLE
SD card switch invisible in SELECT menu, when launching flashcard with SD Access in Slot-1 enabled

### ISSUE THREAD

**Issue by CaiMiao** [DS-Homebrew/TWiLightMenu#1811]
**Console Configuration:**  new3dsxl with dsone sdhc (non-i) inserted. both have twl++ installed
**TWiLight Menu++ Version:** v24.0.0-972f588
**TWiLight Menu++ Theme:** dsi

### Expected behaviour
have s1sd switch on select menu

### Actual behaviour
- when ''scfg access in s1'' + ''sd access in s1'' +'' s1sd access'' enabled
  - no s1sd switch on select menu
    - have launch s1 card instead
  - no fat: on gm9i
- when ''scfg access in s1 enabled'', ''sd access in s1'' + ''s1sd access'' disabled, launch s1 card in select menu
  - console sd card is accessed
  - no s1sd switch on select menu
    - no launch s1 card
  - have sd: and fat: in gm9i

### Steps to reproduce

1. install twilight menu ++ on both end
2. launch from 3ds home
3. call select menu

**Comment by lifehackerhansol** [comment]
The only cart that can be accessed without launching Slot-1 is the R4 Ultra and the Acekard 2 line. This setting is **Slot-1 microSD access.** This is different from **SD access in Slot-1,** which is explained below (essentially, it's the opposite of what Slot-1 microSD access does.)

To access the flashcart SD and console SD both, you need both **SD access in Slot-1** and **SCFG access in Slot-1** enabled.

Having SD access in Slot-1 and SCFG access in Slot-1, then launching my DSONE SDHC indeed can access both the flashcart SD and the console SD, using the SELECT+UP and SELECT+DOWN combo.

However, the SELECT menu's SD card switch is missing. That should be fixed.

**Comment by RocketRobz** [comment]
Closed by 14b5496

**Comment by CaiMiao** [comment]
With SCFG access in Slot-1: ON and SD access in Slot-1: OFF , it still have console SD access via key combo or SELECT menu.

and icons not fixed
![IMG_20220221_154658983](https://user-images.githubusercontent.com/4640483/154911619-c2a10585-a701-4516-a38e-46ac598be08b.jpg)

**Comment by lifehackerhansol** [comment]
Issue superseded by https://github.com/DS-Homebrew/TWiLightMenu/issues/1857.
